### ISSUE TITLE
updating the README file

### ISSUE THREAD

**Issue by atabak-alishiri** [UBC-MDS/522-workflows-group-18#24]
Populating the Readme file based on the guidelines.

**Comment by salva-u** [comment]
I think in the dependencies section we can add : "Python and packages listed in [environment.yml]"
- for the dataset part, maybe we can replace it with an about section as we can see in the milestone- suggestion below".
- I have a suggestion for it I will add it here but I can do it differently when we discuss at 1:30"
- The objective of our analysis was to predict the learning ability of induviduals by way of predicting their scores on the english speaking test in the quiz ( to measure english proficiency) based on their demographic information and their languages background in terms of how much time they've spent in english speaking countries, their primary and native language, etc.
We attempt to build a regression model by using Ridge Model and Lasso Model and measure the model's performance by using R-squared, Root Mean Squared Error, Negative Mean Squared Error. ADD DETAILS ABOUT MODEL CONCLUSIONS...

The dataset we used was collected from 680,333 ( between the ages of 7 and 89) participants were asked to fill an english grammar quiz, additionally their demographic information, and additional details about their language background and countries they've lived in was collected. This dataset was used in the research paper titled "A critical period for second language acquisition: Evidence from 2/3 million
English speakers" by Joshua K. Hartshornea,b,⁎, Joshua B. Tenenbauma, Steven Pinkerc. who collected the dataset described above in order to study the ultimate attainment of grammar-learning ability, specifically looking at the preservation of this ability throughout childhood and its rapid decline in late adolescence. The authors conducted analyses and compared various models to determine the age-related patterns of language acquisition.The dataset can be found here https://osf.io/pyb8s/. We had to use a subset ( 30% of full dataset) of the dataset for milestone 1 the script used to obtain the subset can be found in `src/Sampling from dataset.ipynb`, during later releases of the project we would consider using the full dataset."
